version: '3.7'
name: tracker_app
services:
  frontend:
    container_name: frontend
    build:
      context: ../frontend/
      dockerfile: ../docker/frontend/Dockerfile
      target: dev
    volumes:
      - ../frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      - PORT=${FRONTEND_PORT}
    command: yarn start-frontend
    depends_on:
      - tracker_postgres
  backend:
    container_name: backend
    build:
      context: ../backend/
      dockerfile: ../docker/backend/Dockerfile
      target: dev
    volumes:
      - ../backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${API_PORT}:3000
    command: yarn start:dev
    env_file:
      - .env.dist
    depends_on:
      - tracker_postgres
  tracker_postgres:
    container_name: tracker_postgres
    image: postgres:15.3-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
